### ISSUE TITLE
Can not open the link of https://github.com/tpet/data.git

### ISSUE THREAD

**Issue by SMU-Terry** [ctu-vras/depth_correction#2]
Hi~ RuslanAgishev and Tomas Petricek:
I have to say that it is a fanncy work with intensive workload. But when I tried to learn from it and followed the instruction of doc/install.md, I just found that the https://github.com/tpet/data.git link failed. Can you re-upload it? And what is the use of this data repo?
Looking forward for your reply!

**Comment by RuslanAgishev** [comment]
Hi.
We have used the datasets wrappers (pytorch dataloaders) from the "data" package. Currently, the dependency on the mentioned package is removed and the necessary wrappers are provided in the [src/depth_correction/](https://github.com/ctu-vras/depth_correction/tree/main/src/depth_correction) folder. Please, have a look at the updated installation instructions.
