### ISSUE TITLE
About the pipeline in the work

### ISSUE THREAD

**Issue by xiaojxkevin** [ctu-vras/depth_correction#4]
Hi, sorry for bothering. After I look closer at your work, I have a question for the pipeline designed.
The pipeline provided in paper and `Google drive slides` are slightly different (pipelines are shown below).
<img src = "https://github.com/ctu-vras/depth_correction/assets/87423167/d8cc7a88-c2bc-4bec-867f-4716a483776f" width=400 height=200/>
<img src = "https://github.com/ctu-vras/depth_correction/assets/87423167/32cb0700-5afb-4f71-8b6f-20682f5b1dc5" width=400 height=200/>

In the paper, I notice that there's one more line (connecting `scan` and `SLAM`) added in the pipeline, and there seems to be no such implementation in the codes provided. Thus, I think the pipeline in the slides are more accurate. I am wondering which pipeline is designed for this work.

**Comment by RuslanAgishev** [comment]
Hi. Thank you for the good question. Indeed, we did not use a differentiable SLAM algorithm during the optimization process (it could be an interesting question for future work). By introducing this arrow from a corrected scan to the SLAM, we would like to highlight that the depth correction method could improve localization and mapping using a more accurate input.

**Comment by xiaojxkevin** [comment]
Thanks for the answer.
And there's one more thing: would you upload the checkpoints (weights)?
Thanks!

**Comment by RuslanAgishev** [comment]
I remember about the request, thanks. Sorry for the delay. I will let you know once it's done.

**Comment by xiaojxkevin** [comment]
Thanks for your consideration. Best wishes.
